### ISSUE TITLE
Not support promotion

### ISSUE THREAD

**Issue by jcgdjob** [BitBagCommerce/SyliusProductBundlePlugin#10] opened 2020-08-19 06:15 UTC
Step to reproduce
1) Create a promotion with cart total reach $500 could enjoy $10 discount.
2) Add bundle item with item total > $500
3) apply discount code
4) invalid code

**Comment by BartoszWojdalowicz** [comment] 2021-04-21 09:34
Hi, i try update bundle to sylius 1.9 for BitBag. I reproduce your promo and in my case this problem doesn't exist. If i make promotion and  generate coupons corectly, everything is working. So if this problem exist in older version, in newest should be fixed. 

![image](https://user-images.githubusercontent.com/50419023/115531320-ec678980-a294-11eb-9f4a-d8c0b5c973e3.png)

**Comment by damonsson** [comment] 2021-04-27 07:37
Looks like solved, if not please let us know.

**Closed by damonsson** 2021-04-27 07:37 UTC
